language: php

sudo: false

matrix:
    include:
        - php: 7.2
        - php: 7.2
        - php: 7.3
        - php: 7.3
        - php: 7.4snapshot
        - php: 7.4snapshot
    allow_failures:
        - php: 7.4snapshot
        - php: 7.4snapshot
