language: php

sudo: false

matrix:
    include:
        - php: 7.2
        - php: 7.2
        - php: 7.3
        - php: 7.3
        - php: 7.4snapshot
        - php: 7.4snapshot
    allow_failures:
        - php: 7.4snapshot
        - php: 7.4snapshot

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    # Install various build dependencies. We use `travis_retry` because Composer
    # will occasionally fail intermittently.
    - travis_retry composer install
