language: php

sudo: false

matrix:
    include:
        - php: 7.1
          env: AUTOLOAD=1
        - php: 7.1
          env: AUTOLOAD=0
        - php: 7.2
          env: AUTOLOAD=1
        - php: 7.2
          env: AUTOLOAD=0
        - php: 7.3
          env: AUTOLOAD=1
        - php: 7.3
          env: AUTOLOAD=0
        - php: 7.4snapshot
          env: AUTOLOAD=1
        - php: 7.4snapshot
          env: AUTOLOAD=0
    allow_failures:
        - php: 7.4snapshot
          env: AUTOLOAD=1
        - php: 7.4snapshot
          env: AUTOLOAD=0
